services:
  jenkins:
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile.jenkins
    container_name: oecd-jenkins
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../:/workspace/oecd-analytics-platform
    environment:
      - JENKINS_OPTS=--httpPort=8080
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    networks:
      - oecd-network
    restart: unless-stopped

volumes:
  jenkins_home:

networks:
  oecd-network:
    driver: bridge
