services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: oecd-jenkins
    privileged: true
    user: root
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    # environment:
    #   - JENKINS_OPTS="--prefix=/jenkins"
    networks:
      - oecd-network

volumes:
  jenkins-data:

networks:
  oecd-network:
    external: true
    name: docker_oecd-network
