global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # PostgreSQL metrics
  - job_name: "postgresql"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  # Node metrics
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]

  # Prometheus self-monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # API metrics
  - job_name: "api"
    static_configs:
      - targets: ["api:8000"]
    metrics_path: "/metrics"
